CREATE DATABASE IF NOT EXISTS lexico_db;

USE lexico_db;

CREATE TABLE TIPOSIMBOLO (
  idTipoSimbolo INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(6) NOT NULL,
  CONSTRAINT TIPOSIMBOLO_PK PRIMARY KEY (idTipoSimbolo)
) ENGINE=INNODB;

CREATE TABLE SIMBOLO (
  codigoSimbolo INT NOT NULL,
  termo VARCHAR(100) NOT NULL,
  tipo INT NOT NULL,
  CONSTRAINT SIMBOLO_PK PRIMARY KEY (codigoSimbolo),
  CONSTRAINT SIMBOLO_UQ UNIQUE (termo),
  CONSTRAINT SIMBOLO_TIPOSIMBOLO_FK FOREIGN KEY (tipo)
    REFERENCES TIPOSIMBOLO(idTipoSimbolo)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE sinonimos (
  codigoSimbolo INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  CONSTRAINT sinonimos_UQ UNIQUE (codigoSimbolo, nome),
  CONSTRAINT sinonimos_FK FOREIGN KEY (codigoSimbolo)
    REFERENCES SIMBOLO (codigoSimbolo)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE nocoes (
  codigoSimbolo INT NOT NULL,
  nocao TEXT NOT NULL,
  CONSTRAINT nocoes_FK FOREIGN KEY (codigoSimbolo)
    REFERENCES SIMBOLO (codigoSimbolo) 
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=INNODB;

CREATE TABLE impactos (
  codigoSimbolo INT NOT NULL,
  impacto TEXT NOT NULL,
  CONSTRAINT impactos_FK FOREIGN KEY (codigoSimbolo)
    REFERENCES SIMBOLO (codigoSimbolo)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=INNODB;
