CREATE DATABASE IF NOT EXISTS lexico_db;

USE lexico_db;

CREATE TABLE TIPOSIMBOLO (
  tipoSimboloId INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(6) NOT NULL,
  CONSTRAINT TIPOSIMBOLO_PK PRIMARY KEY (TipoSimboloId)
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE SIMBOLO (
  simboloId INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  tipoSimboloId INT NOT NULL,
  CONSTRAINT SIMBOLO_PK PRIMARY KEY (simboloId),
  CONSTRAINT SIMBOLO_UQ UNIQUE (nome),
  CONSTRAINT SIMBOLO_TIPOSIMBOLO_FK FOREIGN KEY (tipoSimboloId)
    REFERENCES TIPOSIMBOLO(tipoSimboloId)
      ON DELETE RESTRICT
      ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT = 1;

CREATE TABLE sinonimos (
  sinonimoId INT NOT NULL AUTO_INCREMENT,
  simboloId INT NOT NULL,
  nome VARCHAR(100) NOT NULL,
  CONSTRAINT sinonimos_PK PRIMARY KEY (sinonimoId),
  CONSTRAINT sinonimos_UQ UNIQUE (simboloId, nome),
  CONSTRAINT sinonimos_FK FOREIGN KEY (simboloId)
    REFERENCES SIMBOLO (simboloId)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE nocoes (
  nocaoId INT NOT NULL AUTO_INCREMENT,
  simboloId INT NOT NULL,
  descricao TEXT NOT NULL,
  CONSTRAINT nocoes_PK PRIMARY KEY (nocaoId),
  CONSTRAINT nocoes_FK FOREIGN KEY (simboloId)
    REFERENCES SIMBOLO (simboloId) 
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE impactos (
  impactoId INT NOT NULL AUTO_INCREMENT,
  simboloId INT NOT NULL,
  descricao TEXT NOT NULL,
  CONSTRAINT impactos_PK PRIMARY KEY (impactoId),
  CONSTRAINT impactos_FK FOREIGN KEY (simboloId)
    REFERENCES SIMBOLO (simboloId)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=1;
